apiVersion: v1
kind: Pod
metadata:
  name: mock-1
spec:
  containers:
  - name: mock
    image: mock:none
    resources:
      limits:
        cpu: 1
        memory: 1Gi
  nodeSelector:
    virtual-kubelet.io/provider: mock
  tolerations:
  - key: virtual-kubelet.io/provider
    value: mock
    effect: NoSchedule
